spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  application.name: spring-data-polymorphic-example
  datasource:
    url: jdbc:h2:./db/polymorphic_example;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE
    username: sa
    password: admin
server:
  port: 6969

logging.level:
  org.hibernate.type: trace
  io.ibnuja: trace
